[package]
changelog = "CHANGELOG.md"
versioned_files = [
  { path = "moon.mod.json", regex = '"version": "(?<version>\d+\.\d+\.\d+)"' },
  { path = "src/main.mbt", regex = 'version="(?<version>\d+\.\d+\.\d+)"' },
]

[[package.assets]]
path = "artifacts/cbhook-x86_64-linux"

[[package.assets]]
path = "artifacts/cbhook-aarch64-linux"

[[package.assets]]
path = "artifacts/cbhook-aarch64-darwin"

[github]
owner = "mst-mkt"
repo = "cbhook"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch -c release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git add -A"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: prepare release $version"

[workflows.steps.body]
template = "Automated release PR by knope. Merge to tag and release $version."

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"
